### ISSUE TITLE
เพิ่ม Autocomplete ให้กับมหาวิทยาลัย

### ISSUE THREAD

**Issue by Pepewitch** [WebmasterCamp/ywc17-register#19]
เราใช้รับสมัครตามอายุ ไม่ควรบังคับกรอกมหาลัยมั้ยครับ?

คิดว่าควรจะมี checkbox ไม่ได้ศึกษามหาวิทยาลัย

หรือถ้าเป็นไปได้ อยากให้เป็น dropdown + fuzzy search เพื่อที่จะได้ทำสรุปยอดรวมแต่ละมหาลัยลหังจบค่ายได้ครับ

**Comment by wiput1999** [comment]
Ref. https://github.com/MicroBenz/thai-university-database

**Comment by wiput1999** [comment]
เราให้ Form Automated ตรงมหาวิทยาลัย ถ้าเลือกทำงานแล้ว มหาวิทยาลัย คณะ และ สาขา จะเป็น - และ disabled
