### ISSUE TITLE
CSS Radio button ตอน Active จุดไม่อยู่ตรงกลาง

### ISSUE THREAD

**Issue by Pepewitch** [WebmasterCamp/ywc17-register#20]
Test บน Desktop Macbook air googlechrome ครับ
มีทั้งเอียงซ้ายและเอียงบนซ้าย

![image](https://user-images.githubusercontent.com/28859131/63672121-6c60f600-c80b-11e9-9db6-322cec6fa5da.png)

**Comment by wiput1999** [comment]
![image](https://user-images.githubusercontent.com/8299278/63689665-be6a4180-c834-11e9-9b47-b609727b7307.png)
เรากดยังไงก็กลางนะ

**Comment by Pepewitch** [comment]
ถ้าหาไม่เจอ ข้ามไปก่อนก็ได้ มันดูเล็กๆน้อยๆอะ
