### ISSUE TITLE
ไม่ได้ Validate วันเกิด กับ ชั้นปี

### ISSUE THREAD

**Issue by Pepewitch** [WebmasterCamp/ywc17-register#23]

**Comment by Meganest** [comment]
ชั้นปีเนี้ย ไม่ได้ validate เผื่อคนทำงาน หรือไม่ได้เรียนมหาลัยมาสมัคร

**Comment by wiput1999** [comment]
เดี๋ยวเราแก้เรื่องของวันเกิด ให้เลือกได้แค่ช่วงที่เรารับ เดี๋ยวถามบอสให้ว่าเราจะตีกรอบวันเดือนปีเกิดยังไง

**Comment by nutchy** [comment]
@wiput1999 สรุปตอนนี้เป็นยังไงนะ
